#version: '3'
services:

  book-catalog:
    image: task7-b:1
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: task7-b
    ports:
      - "9494:9494"
    environment:
      # - PORT=9494
      - DATABASE_URL=postgresql://task_7_user:EMWpzfgndZwLOfDbbiHRD7AioEsDOT45@dpg-crmbk6lumphs739bnrdg-a.oregon-postgres.render.com/task_7
    restart: "no"

  inventory-management:
    image: task7-i:1
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: task7-i
    ports:
     - "9898:9898"
    environment:
      # - PORT=9898
      - DATABASE_URL=postgresql://task_7_user:EMWpzfgndZwLOfDbbiHRD7AioEsDOT45@dpg-crmbk6lumphs739bnrdg-a.oregon-postgres.render.com/task_7
    restart: "no"